version: 2.1

general:
  artifacts:
    - /app/build/outputs/apk/

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: chmod +x gradlew
      - run:
          command: ./gradlew build